### ISSUE TITLE
[LRNRQ] Add lmer from package lme4

### ISSUE THREAD

**Issue by s-kganz** [mlr-org/mlr3extralearners#197]
### Algorithm

Linear mixed effects (random intercepts *and* random slopes)

### Package

`lme4`

### Supported types

* [ ] classif
* [ ] clust 
* [ ] dens
* [X] regr
* [ ] surv

### I have checked that this is not already implemented in

  * [X] mlr3
  * [X] mlr3learners
  * [X] mlr3extralearners
  * [X] Other core packages (e.g. mlr3proba, mlr3keras)

### Why do I think this is a useful learner?

Linear mixed effects modeling is useful to see how regression slopes vary among groups in a dataset (as in e.g. this paper: https://doi.org/10.1080/IW-6.3.957). In this way, one can determine how interaction terms change according to a covariate not included in the original regression.

### Further Optional Comments

Linear mixed effects modeling is already partially implemented in `mlr3pipelines` via `PipeOpEncodeLmer`. However, this only allows random intercepts. For example, with a response variable `y`, predictors `x1 x2`, and a grouping factor `g`, the pipe operator lets you make a model like `y ~ x1 + x2 + (1 | g)`. However, lme4 supports making models of the form `y ~ (1 + x1 + x2 | g)`. To my knowledge, this is not currently possible in `mlr3` and I think it would be useful to add.

**Comment by sebffischer** [comment]
Hi @s-kganz, thanks for raising this issue! 

1. I think this would be a good addition and 
2. We should implement both regression and classification

Would you be interested in contributing and try to implement it yourself?

**Comment by s-kganz** [comment]
Hi @sebffischer, I'd be happy to give it a shot. I should have availability to work on it over the next few weeks.

**Comment by s-kganz** [comment]
Hi again,

Sorry for the slow work, been bogged down by IRL things recently.

I would like some clarification on what would be good default behavior for this learner. `lmer` has two complications: mixed effects must be specified using a `|` in the formula and all columns in the formula must be explicitly named (you can't use a `.`). This means that either the task or learner needs a mixed effects column explicitly named.

I have an implementation in [my fork](https://github.com/s-kganz/mlr3extralearners/blob/main/R/learner_lme4_regr_lmer.R), but I am unsure how to handle automated tests if I need specific things like a factor column name for the learner to train. As of now it looks for a parameter in either the task or learner to build a valid formula and errors out if none is found. I understand a goal of `mlr3` is to have things work out-of-the-box, but that may not be feasible with this learner.

What would be a good approach for this implementation? Thanks!

**Comment by sebffischer** [comment]
Hey @s-kganz 

There is gam learner from mgcv that also has a special parameter for the formula: https://github.com/mlr-org/mlr3extralearners/blob/main/R/learner_mgcv_classif_gam.R 
My suggestion would be to simply add a parameter `formula`? What do you think? 

For the autotests you can then set this formula before passing the learner to the autotest function.

**Comment by FlorianPargent** [comment]
I am looking for a way to train lme4 models for regression and classification tasks with mlr3 and was very happy to find your excellent regr.lmer learner! Are you still planning to also add a learner for binary classification (e.g. classif.glmer)? This would be really useful for both my teaching and research!
To increase your motivation to maybe add such a learner, I can give two examples: 1) I teach statistical methods for psychologists. This includes predictive modeling based on mlr3 as well as descriptive modeling based on lme4. When I teach predictive modeling, I tell my students how important it is to evaluate the predictive performance of a model based on out-of-sample performance. However, when I teach linear mixed models there is no convenient way to evaluate out-of-sample performance which is frustrating because I think out-of-sample performance evaluation for mixed models is important but rarely done in practice. I love the mlr3 universe and would prefer to run my benchmarks in mlr3 instead of switching to the multilevelmod package in the tidymodels universe. 2) In psychology, ML methods are increasingly applied to study designs previously exclusively analysed with linear mixed models (e.g. experience sampling or smartphone sensing studies). For such research projects, being able to use the lme4 model as a convenient baseline model in my mlr3 benchmark analyses would be great because many psychologists are still very sceptical about applying ML methods in their field.

**Comment by sebffischer** [comment]
Hey @FlorianPargent, thank you for your interest in mlr3 and your elaborate arguments! 
Also for consistency it makes sense to have the classification variant of lme4. 
I will try to implement it soon.
