### ISSUE TITLE
NULL parameter on `xgboost::xgb.importance` function

### ISSUE THREAD

**Issue by bblodfon** [mlr-org/mlr3extralearners#225]
Hi!

This [parameter](https://github.com/mlr-org/mlr3extralearners/blob/main/R/learner_xgboost_surv_xgboost.R#L147) should be `self$model$feature_names` (there is no `self$model$features`). The value is `NULL` and `xgb.importance` uses the `model`'s stored `feature_names` so no issues are caused (atm).

PS: I post this here, since I was testing the first survival xgboost learner, but the same thing is true for the other xgboost learners, e.g. [see](https://github.com/mlr-org/mlr3learners/blob/main/R/LearnerClassifXgboost.R#L153) and [here](https://github.com/mlr-org/mlr3learners/blob/main/R/LearnerRegrXgboost.R#L136). Also, most survival learners were moved from `mlr3proba` (but not removed?) so I thought to better post this here.

**Comment by sebffischer** [comment]
Hi @bblodfon, thank you for raising this issue and your interest in mlr3!

Because we pass a named matrix to `xgb.train` the feature names are available in the model and there is actually no need for us to pass feature names. 

Note that the mlr3proba learners are ported from mlr3learners to mlr3proba, as mlr3proba can currently not be on CRAN, but hopefully will be again in the future!

**Comment by be-marc** [comment]
Fixed by https://github.com/mlr-org/mlr3learners/pull/249
