### ISSUE TITLE
GBM learner predict_types mismatch

### ISSUE THREAD

**Issue by MislavSag** [mlr-org/mlr3extralearners#386]
### Description

When I try to define gbm lerner, I get an error

Error in assert_ordered_set(predict_types, names(mlr_reflections$learner_predict_types[[task_type]]),  : 
  Assertion on 'predict_types' failed: Must be a subset of {'response','se','distr'}, but has additional elements {'quantiles'}.
Calls: %>>% ... assert_ordered_set -> assert_subset -> makeAssertion -> mstop
Execution halted

I chacked in source code and gm really have quantiles element inside predict_types.

Is this allowed or not?

I am usingg dev version of the package.

### Reproducible example

po("learner", learner = lrn("regr.gbm"))

**Comment by bblodfon** [comment]
Hi @MislavSag , I think this was fixed in the most recent `mlr3@0.21.0` CRAN version, see [issue](https://github.com/mlr-org/mlr3/commit/461588ae6a8aa79181e8a13bf92a377365c8e9d9). Can you try with that version? Or maybe we haven't updated yet the `mlr3extralearners` or you need to use the latest release (`0.9.0`).

**Comment by MislavSag** [comment]
It worked with released version of mlr3extralearners. Thanks
