### ISSUE TITLE
Pkgdown not uploading 

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3extralearners#53]
Pkgdown has not been updating for a few weeks now. Need to check root cause. All tests passing and can't see errors in actions.

 @pat-s are you aware of anything that's changed with pkgdown or any other mlr packages that could cause this?

**Comment by pat-s** [comment]
I don't see an issue. Last update was [5 hours ago](https://github.com/mlr-org/mlr3extralearners/tree/gh-pages).

**Comment by RaphaelS1** [comment]
But the vignettes didn't update

**Comment by pat-s** [comment]
Would you mind checking the logs what's happening?

**Comment by pat-s** [comment]
I am not sure which vignette or file is in question since you did not mention one but the vignettes [do update just fine](https://github.com/mlr-org/mlr3extralearners/tree/gh-pages/dev/articles/learners).

You are aware we are building dev and release pkgdown sites automatically based on the version number in DESCRIPTION?

**Comment by RaphaelS1** [comment]
Yeah no I completely forgot that, sorry....
